spring.datasource.url=jdbc:postgresql://localhost:5433/foodlink
spring.datasource.username=postgres
spring.datasource.password=Suprithack@03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
gemini.api.key=${GEMINI_API_KEY}
logging.level.org.springframework.security=DEBUG